# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev:  a8fd79b10319c97cc293dd9e037a8e2c280e20ab
    hooks:
    -  id: black
    -  id: pep257
    -  id: isort

