# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev: c366820a7d4789c0dd21565ecff8bfc4b4c0c78a
    hooks:
    -  id: black
    -  id: pydocstyle
    -  id: isort
    -  id: pytest
    -  id: mypy

