- id: black
  name: black
  entry: /usr/bin/black
  types: [python]
  language: script
  args: ["--check"]

- id: pep257
  name: pep257
  entry: /usr/bin/pep257
  types: [python]
  language: script
  args: ["--ignore=D202,D203"]

- id: isort
  name: isort
  entry: /usr/bin/isort
  types: [python]
  language: script
  args: ["--check"]

- id: pytest
  name: pytest
  entry: /usr/bin/pytest
  types: [python]
  language: script
  args: ["."]
