- id: black
  name: black
  entry: /usr/bin/black
  types: [python]
  language: script
  args: ["--check", "."]

- id: pydocstyle
  name: pydocstyle
  entry: /usr/bin/pydocstyle
  language: script
  files: src/pacdef/*.py
  args: ["--convention=pep257", "--add-ignore=D100,D104,D105", "src", "tests"]

- id: isort
  name: isort
  entry: /usr/bin/isort
  types: [python]
  language: script
  args: ["--check", "."]

- id: pytest
  name: pytest
  entry: /usr/bin/python
  types: [python]
  language: script
  args: ["-m", "pytest", "src", "tests"]

- id: pyright
  name: pyright
  entry: /usr/bin/pyright
  types: [python]
  language: script

- id: bandit
  name: bandit
  entry: /usr/bin/bandit
  files: src/pacdef/*.py
  language: script
  args: ["-c", "pyproject.toml", "-r", "src"]
