# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev: 6a0ab8758268a9321a4d3eb8cc823a1e39680be4
    hooks:
    -  id: black
    -  id: pep257

