# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev: 8a0f921ebc412762f7d1ce0c366eccedbc523dbc
    hooks:
    -  id: black
    -  id: pydocstyle
    -  id: isort
    -  id: pytest
    -  id: pyright
    -  id: bandit

