# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev: 8e5744c948fc9b0dcf2680301c9acbe9ab394104
    hooks:
    -  id: black
    -  id: pydocstyle
    -  id: isort
    -  id: pytest
    -  id: pyright
    -  id: bandit

