# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev: 581c10932fa31f81bd21dcddd033906a311ceed1
    hooks:
    -  id: black
    -  id: pydocstyle
    -  id: isort
    -  id: pytest
    -  id: pyright

