# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev: c17258433c4b14627b1023fb8fedd437c2fd114c
    hooks:
    -  id: black
    -  id: pydocstyle
    -  id: isort
    -  id: pytest
    -  id: mypy

