# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev: fab06f07e0c1bcf04bf6af764b7e36fba5217362
    hooks:
    -  id: black
    -  id: pep257

