# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev: 85c79e75d6c94a1cf26a4f7b74caaf8b22b62591
    hooks:
    -  id: black
    -  id: pydocstyle
    -  id: isort
    -  id: pytest

