- id: black
  name: black
  entry: /usr/bin/black
  types: [python]
  language: script
  args: ["--check", "."]

- id: pydocstyle
  name: pydocstyle
  entry: /usr/bin/pydocstyle
  types: [python]
  language: script
  args: ["--convention=pep257", "--add-ignore=D100,D104,D105", "src", "tests"]

- id: isort
  name: isort
  entry: /usr/bin/isort
  types: [python]
  language: script
  args: ["--check", "."]

- id: pytest
  name: pytest
  entry: /usr/bin/python
  types: [python]
  language: script
  args: ["-m", "pytest", "src", "tests"]

- id: pyright
  name: pyright
  entry: /usr/bin/pyright
  types: [python]
  language: script
