# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ./
    rev:  c6f193faff6fe578fa1a1b9af67256918d7bb612
    hooks:
    -  id: black
    -  id: pep257
    -  id: isort
    -  id: pytest

