name: pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
